--- #YAML:1.0
name:               JSON-Streaming-Writer
version:            0.03
abstract:           Generate JSON output in a streaming manner
author:
    - Martin Atkins <mart@degeneration.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B:         0
    Carp:      0
    IO::File:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
